### ISSUE TITLE
11/18 code review

### ISSUE THREAD

**Issue by cythilya** [neknek25251989/helloworld#12]
# HTML
- `<title>` 缺少內容
- `<input type="submit" name="submit">` 通常 name 不會是 submit

# CSS
- 變數名稱應使用有意義的名字，而非 content 1、content 2、content 3

---

```html
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <link rel="stylesheet" type="text/css" href="/style/css/index.min.css?1508">
</head>
<body>
  <header>
    <a href="#">
      <img src="ruten_logo.png" alt="Ruten Logo">
    </a>
  </header>
  <input type="text" value="請輸入關鍵字"><input type="submit" name="submit">
  <ul>
    <li>買東西</li>
    <li>我的拍賣</li>
    <li>買廣告</li>
  </ul>
  <ul>
    <li><a href="http://www.ruten.com.tw">露天拍賣</a></li> >
    <li>賣東西</li>
  </ul>
  <div class="content1">
    <h1>單品上架</h1>
    <p>適合喜歡自行設定或專業賣家</p>
    <button type="button">使用單品上架</button>
    <ul>
      <li>傳統上傳方式，</li>
      <li>XXXX</li>
      <li>XXXX</li>
      <li>XXXX</li>
    </ul>
  </div>
  <div class="content2">
    <h1>書籍ISBN上架</h1>
    <p>適合沒時間找書籍資料的賣家</p>
    <button type="button">使用ISBN上架</button>
    <ul>
      <li>XXXXX</li>
      <li>XXXXX</li>
      <li>XXXXX</li>
    </ul>
  </div>
  <div class="content3">
    <h1>超簡易上架</h1>
    <p>適合新手或商品</p>
    <button type="button">使用超簡易上架</button>
    <ul>
      <li>XXXX</li>
      <li>XXXX</li>
      <li>XXXX</li>
      <li>XXXX</li>
    </ul>
  </div>
  <div class="content4">
    <h1>Excel上架</h1>
    <p>適合大量快速上架的的賣家</p>
    <button type="button">使用Excel上架</button>
    <ul>
      <li>OOOOO</li>
      <li>OOOOO</li>
      <li>OOOOO</li>
    </ul>
  </div>
  <footer>Footer</footer>
 </body>
</html>
```
```css
.hint {
  background: red;
  color: #fff;
}   
.header {
  background-color: white;
  color: #fff;
}
.breadcrumb {
  background-color: white;
  color: #fff;
}

.content1 {
  background-color: white;
  color: orange;
  float: left;
}
.content2 {
  background-color: white;
  color: purple;
  float: left;
}
.content3 {
  background-color: white;
  color: blue;
  float: left;
}
.content4 {
  background-color: white;
  color: green;
  float: left;
}

```
